
services:
  backend:
    build: ./backend
    container_name: riot-backend
    ports:
      - "5001:5000"
    environment:
      - RIOT_API_KEY=${RIOT_API_KEY}
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build: ./frontend
    container_name: riot-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5001
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
